services:
  planetiler:
    build: .
    entrypoint: ["/scripts/run-planetiler.sh"]
    environment:
      - PBF_URL=${PBF_URL}
    volumes:
      - ./data:/data
    restart: "no"
    
  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "7070:7070"
    volumes:
      - ./data:/data
    command: -p 7070
# TODO NOW how to start after planetiler is finished
#    depends_on:
#      - planetiler
      
  graphhopper:
    build: .
    entrypoint: ["/scripts/run-graphhopper.sh"]
    volumes:
      - ./data:/data
      - ./graphhopper-config.yml:/app/graphhopper/config.yml
    ports:
      - "8989:8989"

  photon:
    build: .
    entrypoint: ["/scripts/run-photon.sh"]
    environment:
      - PHOTON_DB=${PHOTON_DB}
    volumes:
      - ./data:/data
    # expose to other services like geocoder-converter
    expose:
      - "2322"
    ports:
      - "2322:2322"

  geocoder-converter:
    build: .
    entrypoint: ["/scripts/run-geocoder-converter.sh"]
    volumes:
      - ./geocoder-converter-config.yml:/app/geocoder-converter/config.yml
    ports:
      - "8080:8080"
    depends_on:
      - photon

networks:
  default:
    driver: bridge
