services:
  planetiler:
    build:
      context: ./planetiler
    entrypoint: ["/run.sh"]
    environment:
      - PBF_URL=${PBF_URL}
    volumes:
      - ./data:/data
    restart: "no"

  tileserver:
    image: maptiler/tileserver-gl-light:latest
    ports:
      - "7070:8080"
    volumes:
      - ./data:/data
      - ./wait_for.sh:/wait_for.sh:ro
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /wait_for.sh planetiler finished && /usr/src/app/docker-entrypoint.sh"]
    depends_on:
      - planetiler

  graphhopper:
    build:
      context: ./graphhopper
    entrypoint: ["/bin/sh", "-c", "sh /wait_for.sh planetiler starting && /run.sh"]
    volumes:
      - ./data:/data
      - ./wait_for.sh:/wait_for.sh:ro
    ports:
      - "8989:8989"
    # waits for PBF import done by planetiler
    depends_on:
      - planetiler

  photon:
    build:
      context: ./photon
    entrypoint: ["/run.sh"]
    environment:
      - PHOTON_DB=${PHOTON_DB}
    volumes:
      - ./data:/data
    # expose to other services like geocoder-converter
    expose:
      - "2322"
    ports:
      - "2322:2322"

  geocoder-converter:
    build:
      context: ./geocoder-converter
    entrypoint: ["/bin/sh", "-c", "sh /wait_for.sh photon starting && /run.sh"]
    volumes:
      - ./wait_for.sh:/wait_for.sh:ro
      - ./data:/data # for status files
    ports:
      - "8080:8080"
    depends_on:
      - photon
  
  maps:
    build:
      context: ./maps
    entrypoint: ["/bin/sh", "-c", "sh /wait_for.sh planetiler starting && npm run serve"]
    volumes:
      - ./wait_for.sh:/wait_for.sh
      - ./data:/data # for status files
    ports:
      - "3000:3000"
    depends_on:
      - planetiler
    
networks:
  default:
    driver: bridge
